---
title: "homewrok#3"
author: "Tianqi Wang"
date: "October 25, 2016"
output: word_document
---


create a random number and 
divide the data in 10 groups based on the order
```{r}
iris=read.csv("F:\\iris.csv",header=FALSE, stringsAsFactors=FALSE)

colnames(iris)=c("sepalLen","sepalwid","petalLen","petalwid","Class")

set.seed(123456)

random=runif(150)

iris$order=random

y=quantile(random,c(.9,.8,.7,.6,.5,.4,.3,.2,.1))

y

iris$group[random>=y[1]]="A"

iris$group[random<y[1]&random>=y[2]]="B"

iris$group[random<y[2]&random>=y[3]]="C"

iris$group[random<y[3]&random>=y[4]]="D"

iris$group[random<y[4]&random>=y[5]]="E"

iris$group[random<y[5]&random>=y[6]]="F"

iris$group[random<y[6]&random>=y[7]]="G"

iris$group[random<y[7]&random>=y[8]]="H"

iris$group[random<y[8]&random>=y[9]]="I"

iris$group[random<y[9]]="J"

final=iris[,-c(6)]

final

```

use the knn model to predict the test data
```{r}
library(class)

k=5

x=c("A","B","C","D","E","F","G","H","I","J")

prediction=vector(mode="numeric",length=0)

true=vector(mode="numeric",length=0)

for(j in c(1:10)){

train=final[final$group!=x[j],c(1)]
  
test=final[final$group==x[j],c(1)]

cl=final[final$group!=x[j],c(5)]
  
test_true=final[final$group==x[j],c(5)]
  
result=knn(matrix(train,ncol=1),matrix(test,ncol=1),cl,k)

prediction=c(prediction,result)

true=c(true,test_true)

}

m=table(true,prediction)                    #prediction the confusion matrix

m

setosa=c(m[1,1],m[1,2],m[1,3])

versicolor=c(m[2,1],m[2,2],m[2,3])

virginica=c(m[3,1],m[3,2],m[3,3])



n=cbind(setosa,versicolor,virginica)

barplot(n,xlab=c("Iris-setosa"," Iris-versicolor","Iris-virginica"),main="comparion",beside=TRUE,legend=c("Iris-setosa"," Iris-versicolor","Iris-virginica"))







```