---
title: "homework#5"
author: "Tianqi Wang"
date: "November 16, 2016"
output: word_document
---
when using two variable
```{r}
library(e1071)

library(caret)

library(class)

data(iris)

train2=naiveBayes(iris[,1:2],iris[,5])

result2=table(predict(train2,iris[,-5]),iris[,5])

confusionMatrix(predict(train2,iris[,-5]),iris[,5])

benefit2=1*result2[1,1]+3*result2[2,2]+1*result2[3,3]

cost2=10*(result2[1,2]+result2[3,2])

benefit2

cost2

```


when using three variable
```{r}

train3=naiveBayes(iris[,2:4],iris[,5])

result3=table(predict(train3,iris[,-5]),iris[,5])

confusionMatrix(predict(train3,iris[,-5]),iris[,5])

benefit3=1*result3[1,1]+3*result3[2,2]+1*result3[3,3]

cost3=10*(result3[1,2]+result3[3,2])

benefit3

cost3

```


when using one variable
```{r}
train1temp=data.frame(iris[,2],"0")

train1=naiveBayes(train1temp,iris[,5])

result1=table(predict(train1,iris[,-5]),iris[,5])

confusionMatrix(predict(train1,iris[,-5]),iris[,5])

benefit1=1*result1[1,1]+3*result1[2,2]+1*result1[3,3]

cost1=10*(result1[1,2]+result1[3,2])

benefit1

cost1


###we can see that when use three variable, it is more accuate and benefit is more and cost is less

```

when using knn
```{r}

set.seed(123456)

random=runif(150)

iris$order=random

y=quantile(random,c(.9,.8,.7,.6,.5,.4,.3,.2,.1))

y

iris$group[random>=y[1]]="A"

iris$group[random<y[1]&random>=y[2]]="B"

iris$group[random<y[2]&random>=y[3]]="C"

iris$group[random<y[3]&random>=y[4]]="D"

iris$group[random<y[4]&random>=y[5]]="E"

iris$group[random<y[5]&random>=y[6]]="F"

iris$group[random<y[6]&random>=y[7]]="G"

iris$group[random<y[7]&random>=y[8]]="H"

iris$group[random<y[8]&random>=y[9]]="I"

iris$group[random<y[9]]="J"

final=iris[,-c(6)]

k=5

x=c("A","B","C","D","E","F","G","H","I","J")

prediction=vector(mode="numeric",length=0)

true=vector(mode="numeric",length=0)

for(j in c(1:10)){

train=final[final$group!=x[j],c(1)]
  
test=final[final$group==x[j],c(1)]

cl=final[final$group!=x[j],c(5)]
  
test_true=final[final$group==x[j],c(5)]
  
result4=as.character(knn(matrix(train,ncol=1),matrix(test,ncol=1),cl,k))

prediction=c(prediction,result4)

true=c(true,test_true)

}

m=table(true,prediction)                    #prediction the confusion matrix

m

benefit4=1*m[1,1]+3*m[2,2]+1*m[3,3]

cost4=10*(m[1,2]+m[3,2])

benefit4

cost4



















```